### ISSUE TITLE
concurrency: support per-application SPI providers

### ISSUE THREAD

**Issue by FroMage** [eclipse/microprofile-sandbox#17]
In order for mp-concurrency to replace [Reactive Contexts](https://reactiverse.io/reactive-contexts/) which is currently used by RESTEasy to provide context propagation, further to #16 we need to be able to declare providers per application, and not just globally.

When integrating Reactive Contexts in RESTEasy we noticed that in WildFly we had issues because it uses a modular class loader (JBoss Modules) and supports multiple independent deployments of applications.

In this particular case the WildFly distrib was loaded with RESTEasy and Reactive Contexts, and then we had two independent user applications (two `.war` files) that each had their own sets of context providers.

Having a global list of context providers held as a static variable did not work: we needed to have a per-deployment list of context providers.

On deployment, RESTEasy instantiates a new Reactive Contexts subsystem, and stores it in a thread-local (the assumption being that every RESTEasy deployment is tied initially to a separate thread). From there, every thread which serves RESTEasy request has that thread-local propagated and it is used to look up the set of context providers that participate in context propagation.

**Comment by njr-11** [comment]
The requirement to use ServiceLoader (META-INF/services) to plug in third party providers (#15 and #16) sets us in the right direction for this.  Beyond that, it should be straightforward to address this in the spec with requirement listed on the ThreadContextProvider JavaDoc that ThreadContextProviders be loaded from the application's classloader for each deployed module rather than once for the whole server.

**Comment by FroMage** [comment]
What sort of module are you talking about here?

**Comment by FroMage** [comment]
Moved to https://github.com/eclipse/microprofile-concurrency/issues/5
