### ISSUE TITLE
concurrency: support `ThreadContext` lookup without CDI

### ISSUE THREAD

**Issue by FroMage** [eclipse/microprofile-sandbox#18]
In order for mp-concurrency to replace [Reactive Contexts](https://reactiverse.io/reactive-contexts/) which is currently used by RESTEasy to provide context propagation, I suspect we will need to be able to obtain a `TreadContext` implementation without CDI, because RESTEasy-core does not depend on CDI.

Keeping the dependencies of mp-concurrency would allow it to be more broadly used. A CDI implementation could be provided as an optional dependency.

**Comment by njr-11** [comment]
I agree there must be no dependencies on the other specs, even CDI.  The initial proposal and the updates under #15 were intended to be consistent with this.  However, one place where I can see a possible inconsistency is in the ThreadContextConfig/ManagedExecutorConfig default values used for thread context propagation when not otherwise configured.  We ought to clarify here that a specified type of context is only captured and propagated if a thread context provider of that type is available, and that errors must not be raised when a thread context provider isn't available.  Would that satisfy the concern here?  Besides this, which can be addressed in the manner described, I don't see any other dependency on specific context types.

**Comment by FroMage** [comment]
Yes I meant that I only see a way to access the `ThreadContext` via `@Inject`. I don't want to rely on EE Concurrency either because RESTEasy and Weld can both run outside of an EE container, and context propagation should work in SE too.

**Comment by njr-11** [comment]
Thanks for clarifying.  You have a good point there and it is definitely something we want to allow for.  I previously mentioned the builder pattern as a more comprehensive solution, but there are also simpler options such as a static method on ThreadContext (and ManagedExecutor) to obtain an instance that propagates all provided context types.  And I'm sure there are plenty of other possible approaches besides these.  Do you have specific ideas to consider here?

**Comment by FroMage** [comment]
Moved to https://github.com/eclipse/microprofile-concurrency/issues/6
