### ISSUE TITLE
concurrency: support context propagator SPI

### ISSUE THREAD

**Issue by FroMage** [eclipse/microprofile-sandbox#19]
In order for mp-concurrency to replace [Reactive Contexts](https://reactiverse.io/reactive-contexts/) which is currently used by RESTEasy to provide context propagation, it would be very useful if there could be an SPI to declare custom context propagators.

For example, RxJava 1 and 2 both support a plugin system where it is relatively easy to implement automatic context propagation with a context API such as mp-concurrency and Reactive Contexts.

Supporting an SPI for context propagators is as simple as defining an interface with a single `setup` method, and an entry in `META-INF/services` to declare implementations.

With this in hand, mp-concurrency could provide two optional dependencies that provide implementations that hook into RxJava 1 and 2 in order to use mp-concurrency context propagation to propagate contexts automatically to all RxJava pipelines, rather than require users to implement it themselves or depend on a third-party library.

**Comment by njr-11** [comment]
The ContextState.install/restore API from Reactive Contexts (linked above) worries me a bit because I could see it leading to the possibility of applications leaking context, but I don't think we need to go that far in order to enable what you are wanting to do.  It ought to be possible to accomplish as much with just the ThreadContextProvider SPI.  What you are describing seems very useful and I agree is a good integration point to provide, but I wonder if it would better be done as separate from the mp-concurrency spec in order to avoid coupling to a specific version of RxJavaHooks that might possibly change over time?

**Comment by njr-11** [comment]
Thanks for clarifying about the implementations, not the spec, providing the plugins.  That makes much more sense.  Can you elaborate more on the specifics, maybe by walking through an example of what mp-concurrency would define the propagator SPI as and how it would be implemented?  When I looked at the RxJava link, it seems to already have a plugin point to the ServiceLoader, META-INF/services/io.reactiverse.reactivecontexts.core.ContextPropagator, that is defined by RxJava.  So I assume the plugin would be an implementation of this RxJava interface (and utilizing ThreadContextProvider SPI) rather than of a propagator interface defined by mp-concurrency.  I might be missing something here, but I don't see what change would be made to enable this other than calling this out/recommending it for implementations.

**Comment by FroMage** [comment]
Moved to https://github.com/eclipse/microprofile-concurrency/issues/7
